import React from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import Svg, { Polyline, Circle as SvgCircle, Line, Text as SvgText } from 'react-native-svg';
import { BlurView } from 'expo-blur';
import { Colors, Fonts, Spacing, Radii, Shadows } from '@/constants/theme';

// Mock data for the mood chart
const MOCK_MOOD_DATA = [
  0.4, 0.5, 0.6, 0.45, 0.7, 0.65, 0.3, 0.5, 0.55, 0.8,
  0.75, 0.6, 0.4, 0.5, 0.65, 0.7, 0.8, 0.55, 0.45, 0.6,
  0.7, 0.75, 0.8, 0.65, 0.5, 0.6, 0.85, 0.7, 0.6, 0.75,
];

const MOCK_THEMES = [
  { label: 'Work stress', color: Colors.primaryLight },
  { label: 'Sleep', color: Colors.primaryLightest },
  { label: 'Relationships', color: '#F5D6A0' },
  { label: 'Exercise', color: '#D4E7C5' },
  { label: 'Gratitude', color: '#E8D5F0' },
];

const CHART_WIDTH = 320;
const CHART_HEIGHT = 160;
const CHART_PADDING = 20;

function MoodChart() {
  const plotWidth = CHART_WIDTH - CHART_PADDING * 2;
  const plotHeight = CHART_HEIGHT - CHART_PADDING * 2;

  const points = MOCK_MOOD_DATA.map((value, i) => {
    const x = CHART_PADDING + (i / (MOCK_MOOD_DATA.length - 1)) * plotWidth;
    const y = CHART_PADDING + (1 - value) * plotHeight;
    return { x, y };
  });

  const polylinePoints = points.map((p) => `${p.x},${p.y}`).join(' ');

  return (
    <View style={styles.chartCard}>
      <Text style={styles.chartLabel}>Mood over 30 days</Text>
      <View style={styles.chartContainer}>
        <Svg width={CHART_WIDTH} height={CHART_HEIGHT}>
          {/* Horizontal grid lines */}
          {[0.25, 0.5, 0.75].map((v) => {
            const y = CHART_PADDING + (1 - v) * plotHeight;
            return (
              <Line
                key={v}
                x1={CHART_PADDING}
                y1={y}
                x2={CHART_WIDTH - CHART_PADDING}
                y2={y}
                stroke={Colors.border}
                strokeWidth={0.5}
              />
            );
          })}
          {/* Mood line */}
          <Polyline
            points={polylinePoints}
            fill="none"
            stroke={Colors.primary}
            strokeWidth={2.5}
            strokeLinecap="round"
            strokeLinejoin="round"
          />
          {/* Dots at data points (every 5th) */}
          {points
            .filter((_, i) => i % 5 === 0)
            .map((p, i) => (
              <SvgCircle
                key={i}
                cx={p.x}
                cy={p.y}
                r={3.5}
                fill={Colors.primary}
              />
            ))}
          {/* Axis labels */}
          <SvgText
            x={CHART_PADDING}
            y={CHART_HEIGHT - 4}
            fontSize={10}
            fill={Colors.textMuted}
            fontFamily={Fonts.sansRegular}
          >
            30d ago
          </SvgText>
          <SvgText
            x={CHART_WIDTH - CHART_PADDING - 30}
            y={CHART_HEIGHT - 4}
            fontSize={10}
            fill={Colors.textMuted}
            fontFamily={Fonts.sansRegular}
          >
            Today
          </SvgText>
        </Svg>
      </View>
    </View>
  );
}

export default function InsightsScreen() {
  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Your Patterns</Text>
          <Text style={styles.subtitle}>Based on 24 logs over 3 weeks</Text>
        </View>

        {/* Weekly Reflection Card */}
        <View style={styles.reflectionCard}>
          <Text style={styles.reflectionHeading}>This week</Text>
          <Text style={styles.reflectionBody}>
            You've been talking about work and feeling more anxious than usual.
            But there's a pattern -- your mood lifts on days you mentioned exercise
            or being outside. Something to lean into?
          </Text>
          <Text style={styles.aiLabel}>generated by AI</Text>
        </View>

        {/* Mood Chart */}
        <MoodChart />

        {/* Top Themes */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Top Themes</Text>
          <View style={styles.themesRow}>
            {MOCK_THEMES.map((theme) => (
              <View
                key={theme.label}
                style={[styles.themePill, { backgroundColor: theme.color }]}
              >
                <Text style={styles.themePillText}>{theme.label}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Upgrade CTA */}
        <View style={styles.upgradeCardWrapper}>
          <View style={styles.upgradeCard}>
            <View style={styles.upgradeContent}>
              <Ionicons name="lock-closed" size={32} color={Colors.primary} />
              <Text style={styles.upgradeTitle}>
                Unlock full insights
              </Text>
              <Text style={styles.upgradeSubtitle}>
                Deeper patterns, weekly summaries, and personalized suggestions.
              </Text>
              <Pressable style={styles.upgradeButton}>
                <Text style={styles.upgradeButtonText}>
                  Upgrade to Pro -- $4.99/month
                </Text>
              </Pressable>
            </View>
          </View>
          <BlurView
            intensity={40}
            tint="light"
            style={StyleSheet.absoluteFill}
          />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  header: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing.md,
  },
  title: {
    fontFamily: Fonts.serifItalic,
    fontSize: 32,
    color: Colors.textPrimary,
    marginBottom: Spacing.xs,
  },
  subtitle: {
    fontFamily: Fonts.sansRegular,
    fontSize: 14,
    color: Colors.textSecondary,
  },
  // Weekly reflection
  reflectionCard: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.lg,
    backgroundColor: Colors.surface,
    borderRadius: Radii.md,
    padding: Spacing.lg,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
    ...Shadows.card,
  },
  reflectionHeading: {
    fontFamily: Fonts.serifItalic,
    fontSize: 20,
    color: Colors.textPrimary,
    marginBottom: Spacing.sm,
  },
  reflectionBody: {
    fontFamily: Fonts.sansRegular,
    fontSize: 15,
    color: Colors.textPrimary,
    lineHeight: 23,
    marginBottom: Spacing.sm,
  },
  aiLabel: {
    fontFamily: Fonts.sansLight,
    fontSize: 11,
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  // Chart
  chartCard: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.lg,
    backgroundColor: Colors.surface,
    borderRadius: Radii.md,
    padding: Spacing.md,
    ...Shadows.card,
  },
  chartLabel: {
    fontFamily: Fonts.sansMedium,
    fontSize: 14,
    color: Colors.textSecondary,
    marginBottom: Spacing.sm,
  },
  chartContainer: {
    alignItems: 'center',
  },
  // Themes
  section: {
    paddingHorizontal: Spacing.lg,
    marginBottom: Spacing.lg,
  },
  sectionTitle: {
    fontFamily: Fonts.sansMedium,
    fontSize: 16,
    color: Colors.textPrimary,
    marginBottom: Spacing.sm,
  },
  themesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  themePill: {
    borderRadius: Radii.full,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  themePillText: {
    fontFamily: Fonts.sansMedium,
    fontSize: 13,
    color: Colors.textPrimary,
  },
  // Upgrade CTA
  upgradeCardWrapper: {
    marginHorizontal: Spacing.lg,
    borderRadius: Radii.md,
    overflow: 'hidden',
    marginBottom: Spacing.lg,
  },
  upgradeCard: {
    backgroundColor: Colors.surface,
    padding: Spacing.xl,
    ...Shadows.cardLarge,
  },
  upgradeContent: {
    alignItems: 'center',
    gap: Spacing.sm,
  },
  upgradeTitle: {
    fontFamily: Fonts.serifItalic,
    fontSize: 20,
    color: Colors.textPrimary,
    textAlign: 'center',
  },
  upgradeSubtitle: {
    fontFamily: Fonts.sansRegular,
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  upgradeButton: {
    backgroundColor: Colors.primary,
    borderRadius: Radii.md,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    marginTop: Spacing.sm,
  },
  upgradeButtonText: {
    fontFamily: Fonts.sansMedium,
    fontSize: 15,
    color: '#FFFFFF',
  },
});
